branch-defaults:
  master:
    environment: ucd-capstone-fe-v5
    group_suffix: null
global:
  application_name: ucd-capstone-fe-v5
  branch: null
  default_ec2_keyname: MyPrivateKey
  default_platform: Docker 18.09.9-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
